name: mini_zivpn
description: A professional xSocks core for ZIVPN with optimized tunnel and DNS fixes. # Enabled --udpgw-remote-server-addr for Android
publish_to: 'none'
version: 1.0.22+17

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  package_info_plus: ^8.0.0
  open_filex: ^4.3.2
  rxdart: ^0.27.7
  archive: ^3.3.7
  file_picker: ^8.0.0
  share_plus: ^9.0.0
  intl: ^0.19.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
