name: mini_zivpn
description: Optimized xSocks core with 64KB TCP/UDP buffers, standard UDPGW, AutoPilot, and clean UI.
publish_to: 'none'
version: 1.0.24+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  package_info_plus: ^8.0.0
  open_filex: ^4.3.4
  rxdart: ^0.27.7
  archive: ^3.5.1
  file_picker: ^8.0.3
  share_plus: ^9.0.0
  intl: ^0.19.0
  shizuku_api: 1.2.1
  url_launcher: ^6.2.6
  provider: ^6.1.2
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
